"""Lh052 — Conformant AP203 file rejected at the `DATA;` boundary (differential).

Catalog claim: a fully-conformant Part-21 AP203 file (HOOPS-Exchange-style
header: a `/* File generated by ... */` comment inside HEADER, a spaced
`FILE_SCHEMA( ( '...' ) )` list, an ISO-8601 timestamp with an explicit UTC
offset) is accepted by OCCT / HOOPS but has been observed to make a strict
independent tokenizer abort at the `DATA;` section boundary. This is an
independent-parser leniency-gap: every individual token is legal, yet the
strict reader rejects the conformant file.

The DATA section carries a valid minimal planar face so a tolerant reader
loads it without error (load == "ok").

Reproducer recipe: header with `/* File generated ... */` comment, spaced
`FILE_SCHEMA( ('AP203_CONFIGURATION_CONTROLLED_3D_DESIGN_OF_MECHANICAL_PARTS_AND_ASSEMBLIES_MIM_LF') )`,
timestamp `2025-03-05T17:10:01+01:00`, followed by a legal DATA section.

Byte assertions:
  contains(b'File generated by')
  matches(rb'FILE_SCHEMA\(\s+\(')
  contains(b'AP203_CONFIGURATION_CONTROLLED_3D_DESIGN')

Tier-3: load == "ok"
Expected: occt=empty/empty gmsh=empty ifc=schema_n/a  (provisional)

Pattern-mined from ricosjp/ruststep#252 (Apache-2.0/MIT — pattern only;
original attached file is proprietary and was NOT ingested).
"""
from step_corpus.step_builder import StepFile

f = StepFile(
    catalog_id="Lh052",
    defect=(
        "conformant AP203 file rejected at the DATA boundary by a strict "
        "independent parser; the header carries a HOOPS-Exchange-style "
        "/* File generated by ... */ comment inside HEADER, a spaced "
        "FILE_SCHEMA( ( '...' ) ) list, and an ISO-8601 timestamp with an "
        "explicit +01:00 UTC offset; every individual token is legal Part-21 "
        "and OCCT/HOOPS accept the file, yet a strict independent tokenizer has "
        "been observed to abort at the DATA; section boundary; "
        "independent-parser leniency gap / interop differential; "
        "expected kernel behavior: accept — the file is conformant Part-21"
    ),
)


def _render_conformant_ap203() -> str:
    return (
        "ISO-10303-21;\n"
        f"/* {f.catalog_id}: conformant AP203 rejected at DATA boundary by strict independent parsers */\n"
        "HEADER;\n"
        "/* File generated by a conformant AP203 exporter (HOOPS-Exchange-style). */\n"
        "FILE_DESCRIPTION(('Lh052 conformant AP203 differential'),'2;1');\n"
        "FILE_NAME('Lh052.stp','2025-03-05T17:10:01+01:00',(''),(''),\n"
        "  'cad-research-suite','','');\n"
        "FILE_SCHEMA( ('AP203_CONFIGURATION_CONTROLLED_3D_DESIGN_OF_MECHANICAL_PARTS_AND_ASSEMBLIES_MIM_LF') );\n"
        "ENDSEC;\n"
        "DATA;\n"
        "/* Legal DATA section: a valid minimal planar face. A tolerant reader\n"
        "   loads this without error; a strict independent tokenizer has been\n"
        "   observed to abort at the DATA; boundary on such conformant files. */\n"
        "#1=CARTESIAN_POINT('',(0.,0.,0.));\n"
        "#2=CARTESIAN_POINT('',(10.,0.,0.));\n"
        "#3=CARTESIAN_POINT('',(10.,10.,0.));\n"
        "#4=CARTESIAN_POINT('',(0.,10.,0.));\n"
        "#5=DIRECTION('',(1.,0.,0.));\n"
        "#6=DIRECTION('',(0.,1.,0.));\n"
        "#7=DIRECTION('',(0.,0.,1.));\n"
        "#8=VECTOR('',#5,10.);\n"
        "#9=VECTOR('',#6,10.);\n"
        "#10=LINE('',#1,#8);\n"
        "#11=LINE('',#2,#9);\n"
        "#12=VECTOR('',#5,10.);\n"
        "#13=LINE('',#4,#12);\n"
        "#14=VECTOR('',#6,10.);\n"
        "#15=LINE('',#1,#14);\n"
        "#16=VERTEX_POINT('',#1);\n"
        "#17=VERTEX_POINT('',#2);\n"
        "#18=VERTEX_POINT('',#3);\n"
        "#19=VERTEX_POINT('',#4);\n"
        "#20=EDGE_CURVE('',#16,#17,#10,.T.);\n"
        "#21=EDGE_CURVE('',#17,#18,#11,.T.);\n"
        "#22=EDGE_CURVE('',#19,#18,#13,.T.);\n"
        "#23=EDGE_CURVE('',#16,#19,#15,.T.);\n"
        "#24=ORIENTED_EDGE('',*,*,#20,.T.);\n"
        "#25=ORIENTED_EDGE('',*,*,#21,.T.);\n"
        "#26=ORIENTED_EDGE('',*,*,#22,.F.);\n"
        "#27=ORIENTED_EDGE('',*,*,#23,.F.);\n"
        "#28=EDGE_LOOP('',(#24,#25,#26,#27));\n"
        "#29=AXIS2_PLACEMENT_3D('',#1,#7,#5);\n"
        "#30=PLANE('',#29);\n"
        "#31=FACE_OUTER_BOUND('',#28,.T.);\n"
        "#32=ADVANCED_FACE('',(#31),#30,.T.);\n"
        "#33=OPEN_SHELL('',(#32));\n"
        "#34=SHELL_BASED_SURFACE_MODEL('',(#33));\n"
        "ENDSEC;\n"
        "END-ISO-10303-21;\n"
    )


f.render = _render_conformant_ap203  # type: ignore[method-assign]
