"""Ad120 — SURFACE_OF_REVOLUTION on 3-point-arc profile crashes consumer on import.

Catalog claim: a SURFACE_OF_REVOLUTION generated by revolving a 3-point-arc
profile around its near-perpendicular axis produces a STEP file that crashes
some receivers on import. The geometric pattern: profile is a B-spline curve
approximating a 3-point arc whose tangent at one endpoint is nearly parallel
to the revolution axis, creating a near-degenerate revolution surface.

Source: pattern-mined from FreeCAD/FreeCAD#16681 (LGPL-clean — pattern only,
no bytes copied). FreeCAD-reported bug: 'Arc by 3 points + 360 revolution
create a STEP model that crashes upon import'. The reproducer involves
sketcher's arc-by-3-points tool, which produces a B-spline approximation,
revolved around the sketch vertical axis.

LGPL-clean: pattern-matched, no bytes copied.
"""
from step_corpus.step_builder import StepFile

f = StepFile(catalog_id="Ad120",
             defect="SURFACE_OF_REVOLUTION on near-degenerate arc profile")

# Profile: degree-2 B-spline curve approximating an arc, where one endpoint
# is near the rotation axis (Y axis) — the part the user reports as 'arc
# with one point near axis' that triggers the crash.
# Control points sweep an arc in the XZ plane (Y is the revolution axis):
#   (0, 0, 0)      — endpoint NEAR the Y axis
#   (1, 0, 0.5)
#   (2, 0, 0)      — endpoint AT the Y axis (degenerate tangent)
p0 = f.cartesian_point((0.001, 0.0, 0.0))   # near-axis endpoint (sub-eps offset)
p1 = f.cartesian_point((1.0, 0.0, 0.5))
p2 = f.cartesian_point((2.0, 0.0, 0.0))     # far-from-axis endpoint

profile = f._emit_raw(
    f"B_SPLINE_CURVE_WITH_KNOTS('arc_3pt_profile',2,"
    f"(#{p0.eid},#{p1.eid},#{p2.eid}),"
    ".UNSPECIFIED.,.F.,.F.,(3,3),(0.0,1.0),.UNSPECIFIED.)"
)

# Revolution axis: Y axis through origin.
axis_origin = f.cartesian_point((0.0, 0.0, 0.0))
y_axis = f.direction((0.0, 1.0, 0.0))
axis_line = f._emit_raw(
    f"AXIS1_PLACEMENT('rev_axis',#{axis_origin.eid},#{y_axis.eid})"
)

surf = f._emit_raw(
    f"SURFACE_OF_REVOLUTION('rev_arc',#{profile.eid},#{axis_line.eid})"
)

# Face on the revolved surface for round-trip exercise.
v_near = f.vertex_point(p0)
v_far = f.vertex_point(p2)
d = f.direction((1.0, 0.0, 0.0))
vec = f.vector(d, 2.0)
ln = f.line(p0, vec)
edge = f.edge_curve(v_near, v_far, ln)
loop = f.edge_loop([f.oriented_edge(edge, True)])
face = f.advanced_face([f.face_outer_bound(loop)], surf)
shell = f.open_shell([face])
sbsm = f.shell_based_surface_model([shell])
f.add_product_chain(sbsm)
