"""Programmatic access to ``STEP_PROBLEM_CATALOG.json``.

The catalog ships as a sibling JSON file next to ``STEP_PROBLEM_CATALOG.md``.
It is generated by :mod:`step_corpus._build_catalog_json` and committed to the
repository so that downstream tooling (CI, validators, contributor scripts)
can iterate over canonical entries without parsing markdown.

Typical use::

    from step_corpus import catalog

    for entry in catalog.iter_canonical():
        print(entry["id"], entry["fixture_path"])

    le001 = catalog.find("Le001")
    assert le001 is not None

The schema for each entry is documented in
``research/validation/src/step_corpus/_build_catalog_json.py`` and matches the
``STEP_PROBLEM_CATALOG.json`` file. Required keys::

    id, title, section, section_dir, category, sources, sender, description,
    reproducer, expected_kernel_behavior, notes, expected_validation,
    fixture_path, see_also
"""
from __future__ import annotations

import json
from collections.abc import Iterator
from pathlib import Path
from typing import Any

# This file lives at: research/validation/src/step_corpus/catalog.py
# Research root is parents[3].
_RESEARCH_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CATALOG_PATH = _RESEARCH_ROOT / "STEP_PROBLEM_CATALOG.json"

# Cached load: keyed by resolved path so callers passing different paths each
# get their own cache slot.
_CACHE: dict[Path, list[dict[str, Any]]] = {}


def load_catalog(path: str | Path | None = None) -> list[dict[str, Any]]:
    """Load and return the catalog as a list of dict entries.

    Results are cached per resolved path; pass ``path=None`` (the default) to
    use the canonical ``STEP_PROBLEM_CATALOG.json`` next to the markdown.
    """
    target = Path(path).resolve() if path is not None else DEFAULT_CATALOG_PATH.resolve()
    cached = _CACHE.get(target)
    if cached is not None:
        return cached
    with target.open(encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, list):
        raise ValueError(f"{target}: top-level JSON must be a list of entries")
    _CACHE[target] = data
    return data


def iter_canonical(path: str | Path | None = None) -> Iterator[dict[str, Any]]:
    """Yield each canonical catalog entry in catalog (sorted) order."""
    for entry in load_catalog(path):
        yield entry


def find(entry_id: str, path: str | Path | None = None) -> dict[str, Any] | None:
    """Return the entry whose ``id`` matches ``entry_id`` or ``None``."""
    for entry in load_catalog(path):
        if entry["id"] == entry_id:
            return entry
    return None


__all__ = [
    "DEFAULT_CATALOG_PATH",
    "load_catalog",
    "iter_canonical",
    "find",
]
