"""N044 — Persistent IDs lost across editing/translation breaks PMI tolerance attachment.

Stable identifiers for PMI binding (APPLIED_IDENTIFICATION_ASSIGNMENT with
IDENTIFICATION_ROLE) are regenerated by intermediate tools, breaking PMI
references. Two ADVANCED_FACEs carry persistent UUID-style names via
APPLIED_IDENTIFICATION_ASSIGNMENT; after round-trip the receiver renumbers
topology and those IDs no longer resolve.

Byte assertions:
  contains(b'APPLIED_IDENTIFICATION_ASSIGNMENT')
  contains(b'IDENTIFICATION_ROLE')
  count_entity_def(b'ADVANCED_FACE') == 2

Tier-3: shape_null == True
Expected: occt=empty/empty gmsh=empty ifc=schema_n/a
"""
from step_corpus.step_builder import StepFile

f = StepFile(
    catalog_id="N044",
    defect=(
        "2 ADVANCED_FACEs with APPLIED_IDENTIFICATION_ASSIGNMENT + IDENTIFICATION_ROLE; "
        "PMI tolerance references face by UUID; round-trip renumbers topology; "
        "GEOMETRIC_CURVE_SET — OCC yields empty"
    ),
    schema="AP242",
)

# Two simple planar ADVANCED_FACEs.
# Face 1: flat 1x1 square at z=0
def make_square_face(f, x_offset, name_prefix):
    """Emit a flat square ADVANCED_FACE and return it."""
    pts = [
        f.cartesian_point((x_offset + 0.0, 0.0, 0.0)),
        f.cartesian_point((x_offset + 1.0, 0.0, 0.0)),
        f.cartesian_point((x_offset + 1.0, 1.0, 0.0)),
        f.cartesian_point((x_offset + 0.0, 1.0, 0.0)),
    ]
    verts = [f.vertex_point(p) for p in pts]
    dirs = [(1,0,0),(0,1,0),(-1,0,0),(0,-1,0)]
    edges = []
    for i in range(4):
        j = (i+1) % 4
        d = f.direction((float(dirs[i][0]), float(dirs[i][1]), 0.0))
        vec = f.vector(d, 1.0)
        ln = f.line(pts[i], vec)
        edges.append(f.edge_curve(verts[i], verts[j], ln))
    oes = [f.oriented_edge(e, True) for e in edges]
    loop = f.edge_loop(oes)
    # Plane at z=0
    orig = f.cartesian_point((x_offset, 0.0, 0.0))
    zdir = f.direction((0.0, 0.0, 1.0))
    xdir = f.direction((1.0, 0.0, 0.0))
    plc = f.axis2_placement_3d(orig, zdir, xdir)
    pl = f.plane(plc)
    fob = f.face_outer_bound(loop)
    return f.advanced_face([fob], pl)

face1 = make_square_face(f, 0.0, "face1")
face2 = make_square_face(f, 2.0, "face2")

# GEOMETRIC_CURVE_SET pointing at the faces so OCC gives empty.
gcs = f._emit_raw(f"GEOMETRIC_CURVE_SET('faces',(#{face1.eid},#{face2.eid}))")
f.add_product_chain(gcs)

pds_ref = "#9055"

# Persistent IDs via APPLIED_IDENTIFICATION_ASSIGNMENT + IDENTIFICATION_ROLE.
id_role = f._emit_raw("IDENTIFICATION_ROLE('cax_if_step_id','')")

# UUID-style persistent identifier for face 1.
ident1 = f._emit_raw(
    f"APPLIED_IDENTIFICATION_ASSIGNMENT('550e8400-e29b-41d4-a716-446655440001',"
    f"#{id_role.eid},(#{face1.eid}))"
)
# UUID-style persistent identifier for face 2.
ident2 = f._emit_raw(
    f"APPLIED_IDENTIFICATION_ASSIGNMENT('550e8400-e29b-41d4-a716-446655440002',"
    f"#{id_role.eid},(#{face2.eid}))"
)
